### ISSUE TITLE
game/service.go中func (s *server) recv有bug？

### ISSUE THREAD

**Issue by guoxf** [gonet2/game#3]
https://github.com/gonet2/game/blob/master/src/game/service.go#L37， 这个方法如果不进行recover，在做压力测试的时候几率很大出现panic，错误信息如下：

![image](https://cloud.githubusercontent.com/assets/3947566/13388171/b60a3a14-def8-11e5-8bad-72c50cfa45e9.png)

**Comment by xtaci** [comment]
什么版本的grpc

**Comment by guoxf** [comment]
确实是grpc版本的问题，更新版本后就好了。
