### ISSUE TITLE
user id 类型为 int32 的疑问

### ISSUE THREAD

**Issue by simiwe** [gonet2/game#6]
![image](https://user-images.githubusercontent.com/902283/42358695-8d05d148-8110-11e8-8975-922b0e24a761.png)

user id 不是通过 snowflake 生成的吗？
user 中 Id 为 int32 类型， snowflake 生成的 uuid 为 uint64 。
如果是的话 uint64 -> int32 不是不安全的吗？
如果 user id 是通过其他算法生成的，那怎么保证在分布式系统中的唯一性呢？

**Comment by ZhiqinYang** [comment]
这只是一个测试程序， 更具自己要求改啊！
